<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>MDFlowViewer</AssemblyName>
    <ApplicationIcon>..\..\public\mdflow.ico</ApplicationIcon>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
</Project>
